ALTER TABLE "TitleDepartment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganizationHiddenTitle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgentQuota" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TranscodeJob" ENABLE ROW LEVEL SECURITY;
